# Los volumenes /app, redis y mongo no se sobreescriben en reconstrucciones posteriores con 'build'.
# Para realizar una limpieza total antes de recargar los servicios ejecutar los siguientes comandos antes de 'build'
# - 'docker-compose down --volumes --remove-orphans'
# - 'docker image prune -a -f'

services:

  # -------- SERVICIO REDIS --------
  redis:
      image: redis:7-alpine # Versión oficial de Redis
      volumes:
        - redis-data:/data # Volumen para persistencia
      healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  # -------- SERVICIO MONGO --------
  mongo: 
    image: mongo:6.0 # Verisón oficial de Mongo
    command: ["mongod", "--quiet"] # Silencia logs innecesarios
    volumes: 
      - mongo-data:/data/db # Volumen para persistencia
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mongosh -u $$MONGO_USER -p $$MONGO_PASS --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


    # -------- SERVICIO POSTGRES --------
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # -------- SERVICIO BACKEND (DEV) --------
  backend:
    build:
      context: . # Directorio raíz
      dockerfile: Dockerfile.dev # Localización del Dockerfile
    image: inma_backend_dev # Imagen inmutable
    working_dir: /app # Montar el proyecto en el contenedor para hot-reload
    volumes:
      - ./backend:/app # Volumen que persiste entre reinicios
    ports:
    - "8000:8000"
    env_file:
      - .env # Archivo .env
    command: ["uvicorn", "app.main:app", "--host 0.0.0.0", "--port 8000", "--log-level debug", "--reload"]
    depends_on: # Se ejecuta tras arrancar los servicios de memoria
      - redis
      - mongo
      - posgres